config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/starred_repos', to: 'starred_repos#index'
  get '/repos',         to: 'repos#index'
  get '/followers',     to: 'followers#index'
  get '/following',     to: 'following#index'
  get '/events',        to: 'events#index'
  get '/organizations',   to: 'organizations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/events.rb
class Events

  attr_reader :type, :repo_name, :repo_url, :created_at

  def initialize(attributes = {})
    @type       = attributes[:type]
    @repo_name  = attributes[:repo][:name]
    @repo_url   = attributes[:repo][:url]
    @created_at = attributes[:created_at]
  end

  def self.find_events(user)
    EventsService.find_events(user).map do |event|
      new(event)
    end
  end
end

app/models/events_service.rb
class EventsService
  def self.find_events(user)
    response = Faraday.get("https://api.github.com/users/#{user}/events?client_id=#{ENV['GITHUB_KEY']}&client_secret=#{ENV['GITHUB_SECRET']}")
    JSON.parse(response.body, symbolize_names: true)
  end
end

app/models/followers.rb
class Followers
  attr_reader :user, :avatar, :url

  def initialize(attributes={})
    @user = attributes['login']
    @user = attributes['avatar_url']
    @user = attributes['html_url']
  end

  def self.find_all(username)
    FollowersService.find_all(username).map do |follower|
      new(follower)
    end
  end
end

app/models/followers_service.rb
class FollowersService
  def self.find_all(username)
    response = Faraday.get("https://api.github.com/users/#{username}/followers?client_id=#{ENV['GITHUB_KEY']}&client_secret=#{ENV['GITHUB_SECRET']}")
    JSON.parse(response.body)
  end
end

app/models/following.rb
class Following
  attr_reader :user, :avatar, :url

  def initialize(attributes={})
    @user = attributes['login']
    @user = attributes['avatar_url']
    @user = attributes['html_url']
  end

  def self.find_all(username)
    FollowingService.find_all(username).map do |followed|
      new(followed)
    end
  end
end

app/models/following_service.rb
class FollowingService
  def self.find_all(username)
    response = Faraday.get("https://api.github.com/users/#{username}/following?client_id=#{ENV['GITHUB_KEY']}&client_secret=#{ENV['GITHUB_SECRET']}")
    JSON.parse(response.body)
  end
end

app/models/repos.rb
class Repos

  attr_reader :name, :url, :language

  def initialize(attributes = {})
    @name     = attributes[:name]
    @url      = attributes[:html_url]
    @language = attributes[:language]
  end

  def self.find_repos(user)
    ReposService.find_repos(user).map do |repo|
      new(repo)
    end
  end
end

app/models/repos_service.rb
class ReposService

  def self.find_repos(user)
    response = Faraday.get("https://api.github.com/users/#{user}/repos?client_id=#{ENV['GITHUB_KEY']}&client_secret=#{ENV['GITHUB_SECRET']}")
    JSON.parse(response.body, symbolize_names: true)
  end

end

app/models/starred_repos.rb
class StarredRepos
  attr_reader :owner, :name, :url, :issues
  
  def initialize(attributes = {})
    @owner    = attributes[:owner][:login]
    @name     = attributes[:name]
    @url      = attributes[:html_url]
    @issues   = attributes[:open_issues_count]
  end

  def self.find_repos(user)
    StarredReposService.find_repos(user).map do |repo|
      new(repo)
    end
  end
end

app/models/starred_repos_service.rb
class StarredReposService

  def self.find_repos(user)
    response = Faraday.get("https://api.github.com/users/#{user}/starred?client_id=#{ENV['GITHUB_KEY']}&client_secret=#{ENV['GITHUB_SECRET']}")
    JSON.parse(response.body, symbolize_names: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth(auth)
    user = User.find_or_create_by(provider: auth['provider'], uid: auth['uid'])

    user.nickname          = auth['info']['nickname']
    user.name              = auth['info']['name']
    user.email             = auth['info']['email']
    user.avatar_url        = auth['info']['image']
    user.token             = auth['credentials']['token']

    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize!
    redirect_to root_path unless current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Events.find_events(current_user.nickname)
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = Followers.find_all(current_user.nickname)
  end
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  def index
    @following = Following.find_all(current_user.nickname)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end 

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    @repos = Repos.find_repos(current_user.nickname)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <img src="https://www.coderbox.me/images/github.png" class="kitty-icon navbar-left">
      <%= link_to "Home", root_path, class: "go-home navbar-left" %>
    </div>
  </div>
</nav>

app/views/dashboard/index.html.erb
<%=render partial: 'dashboard/navbar' %>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-3">
      <img id='user-image' src="<%= current_user.avatar_url %>"/>
      <div class="user_name">
        <%= current_user.name %>
      </div>
      <div class="user_nickname">
        <%= current_user.nickname %>
      </div>
      <br>
      <div class="user-orgs">
        <%= link_to "Organizations", organizations_path %>
      </div>
      <br>
      <div class="bio_link">
        <%= link_to "Add a bio", "https://github.com/settings/profile?focus_bio=1" %>
      </div>
    </div>
    <div class="col-9">
        <div class='repo-link'><%= link_to "Repos", repos_path %></div>
        <div class='starred-repo-link'><%= link_to "Starred Repos", starred_repos_path %></div>
        <div class='following-link'><%= link_to "Following", following_path %></div>
        <div class='followers-link'><%= link_to "Followers", followers_path %></div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%=render partial: 'dashboard/navbar' %>
<div class="container login">
  <div class="row">
    <div class="col-3">
      <button class="btn btn-default btn-lg"><%= link_to "Login With Github", "/auth/github" %></button>
    </div>
  </div>
</div>